### PR TITLE
Update messages

### PR DESCRIPTION
**Pull request by sjmog**
Add flash messages with nicer HTML etc. They pin to the bottom of the nav at current, which is a decent temporary solution (not perfect).

There's also slight misalignment but it does the job for now ;)

### CODE REVIEW

**Comment by pitchinvasion** [comment]
Looks a little odd on my local machine

image

**Comment by pitchinvasion** [comment]
Is that the slight misalignment? I wonder if the issue is because my window was narrower

**Comment by sjmog** [comment]
I know why it's happening, but it can only be solved with another wrapper 'div'. And I hate excess HTML.

**Comment by pitchinvasion** [comment]
ok let's just leave it for the mo. :shipit:

**Pull request merged**
